version: "3"

vars:
  BUILD_DIR: bin
  EXECUTABLE: gwc

tasks:
  default:
    cmd: task -a

  build:
    cmds:
      - test -d {{.BUILD_DIR}} || mkdir {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.EXECUTABLE}} src/main.go

  execute:
    deps:
      - build
    cmd: ./{{.BUILD_DIR}}/{{.EXECUTABLE}}
